### ISSUE TITLE
game freezes

### ISSUE THREAD

**Issue by gm1quel** [RusseII/region-chat#9]
Hi,

when i enable the plugin and i try to type the game freezes and i have to restart.
it was working for me a couple of days ago but now i cant get it to work, freezes everytime.

**Comment by gm1quel** [comment]
> Is when you click enter? or when you click the keys?

When i click enter!

**Comment by gm1quel** [comment]
Yes, i am on normal mode

**Comment by RusseII** [comment]
Still testing some things, I'm having trouble reproducing it. 

If you turn on read-only mode does it let you send messages or still crash?

<img width="444" height="264" alt="Image" src="https://github.com/user-attachments/assets/644ecc5a-7346-48a8-a5e5-07acf5850951" />

**Comment by RusseII** [comment]
Still looking into it

Are you running windows? Any other chat plugins that this plugin is maybe conflicting with? 

I have a few ideas on fixes to try, but I'm not able to fully reproduce it so hard to know for sure if the fixes will work.

**Comment by RusseII** [comment]
@gm1quel I made a PR on the runelite repo (https://github.com/runelite/plugin-hub/pull/8630) - I believe those should hopefully fix the issue once it gets merged in. 

Unfortunately, it usually takes a few days for review.

After it gets merged, please post here and LMK if your issue is fixed or not. tysm!

**Comment by RusseII** [comment]
@gm1quel it was merged and is hopefully fixed now - can you try and let me know? Make sure to restart runelite so you get the latest update.

**Comment by gm1quel** [comment]
> [@gm1quel](https://github.com/gm1quel) it was merged and is hopefully fixed now - can you try and let me know? Make sure to restart runelite so you get the latest update.

It is still not working for mee, it freezes when i try to type.
It does work on another account that doenst use the Jagex launcher, so any idea? thanks! (also the other account is not an ironman, the one where it freezes is an iron man? maybe it has something to do with the ironman icon and the white chat icon)

**Comment by Snuchu** [comment]
Yeah, RuneLite just insta-freezes whenever I try to talk in public chat with GC enabled. I am also an ironman, if that's somehow relevant lol

I can also check if my main alt can talk on it without crashing, will report back in a bit.

EDIT 1: My RuneLite also immediately freezes when I try to talk in public on a quest speedrun world.
However, on my alt, which is a normal account, GC seems to be fully functional and nothing is freezing... ***except when I try a QSR world.***

This does indicate a problem relating to the icon beside the name, I think...

**Comment by RusseII** [comment]
I figured out the issue @Snuchu @gm1quel and fixed in https://github.com/runelite/plugin-hub/pull/11885 

It was an issue with the icons. Thanks

**Comment by RusseII** [comment]
It's merged and fixed!
